#pragma once

// Resource IDs shared between app.rc and the C++ sources.
// Icons live in assets\icons\ (generated by assets\icons\make_icons.ps1).
#define IDI_APP            101  // main cascade icon (exe + tray)
#define IDI_MENU_SETTINGS  102  // tray menu: Settings... (gear glyph)
#define IDI_MENU_EXIT      103  // tray menu: Exit (power glyph)
